### ISSUE TITLE
ERC20 balances of holders

### ISSUE THREAD

**Issue by RaKatt** [web3labs/epirus-free#40]
Hello Team,

I wanted to look up all account balances of an ERC20 token.
What I found was a possibility to display all transfers of an ERC20 token.

But there was no feature to show all individual holders balances.

**Comment by SweeXordious** [comment]
Hello,
Sorry for the late reply.
We do not provide that functionality for the free version. However, we can customize Epirus-Explorer for our clients to suit their needs. 
Please reach out to us if you want to further discuss the paid version of the product at support@web3labs.com. 
Thank you.
