### ISSUE TITLE
Error deploying stack, error in nginx-instance

### ISSUE THREAD

**Issue by typoworx-de** [web3labs/epirus-free#42]
Trying to deploy the stack from GIT-URL gives the following error after deployment. All containers are running except nginx-instance. NGINX instance is failing with error:

```
driver failed programming external connectivity on endpoint epirus-free_nginx_1 (d0a08707824f062c7ccb65eb68bbc1baaa49770819e73fa009dfa816561ba7fe): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use
```
The Stack has created it's own docker-network "epirius-net". I can't understand why there is a binding conflict.

**Comment by typoworx-de** [comment]
May be the container is trying to use docker-host port 80 using port-mapping?
https://github.com/web3labs/epirus-free/blob/02003541c50d22dff645591185e34fb106818418/docker-compose.yml#L49

This won't work as my local machine already uses this. Why is this used by default?

**Comment by SweeXordious** [comment]
Hello, 
Sorry for the late reply. 
We are using port 80 for nginx so that we load balance traffic to the correct container and users will have to access the explorer through 80.
You can change it if you want.
Please reopen if there is something else we can help you with.
