### ISSUE TITLE
Error Ingestion In Besu Private Network

### ISSUE THREAD

**Issue by fahadh4ilyas** [web3labs/epirus-free#43]
Here is the error

```
ingestion_1  | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
ingestion_1  | 2021-12-08 17:59:58.830 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
ingestion_1  |
ingestion_1  | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ingestionService' defined in URL [jar:file:/app/app.jar!/BOOT-INF/classes!/io/epirus/explorer/ingestion/app/IngestionService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.epirus.explorer.ingestion.app.IngestionService]: Constructor threw exception; nested exception is java.lang.IllegalStateException: web3j.web3ClientVersion().sendAsync().get().result must not be null
ingestion_1  |  at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:314) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
ingestion_1  |  at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:295) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
ingestion_1  |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
ingestion_1  |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
ingestion_1  |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
ingestion_1  |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
ingestion_1  |  at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
ingestion_1  |  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
ingestion_1  |  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
ingestion_1  |  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
ingestion_1  |  at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
ingestion_1  |  at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
ingestion_1  |  at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
ingestion_1  |  at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
ingestion_1  |  at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
ingestion_1  |  at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
ingestion_1  |  at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
ingestion_1  |  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
ingestion_1  |  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
ingestion_1  |  at io.epirus.explorer.ingestion.app.IngestionApplicationKt.main(IngestionApplication.kt:25) ~[classes!/:na]
ingestion_1  |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
ingestion_1  |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
ingestion_1  |  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
ingestion_1  |  at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
ingestion_1  |  at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[app.jar:na]
ingestion_1  |  at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[app.jar:na]
ingestion_1  |  at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[app.jar:na]
ingestion_1  |  at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) ~[app.jar:na]
ingestion_1  | Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.epirus.explorer.ingestion.app.IngestionService]: Constructor threw exception; nested exception is java.lang.IllegalStateException: web3j.web3ClientVersion().sendAsync().get().result must not be null
ingestion_1  |  at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:213) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
ingestion_1  |  at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
ingestion_1  |  at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:310) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
ingestion_1  |  ... 27 common frames omitted
ingestion_1  | Caused by: java.lang.IllegalStateException: web3j.web3ClientVersion().sendAsync().get().result must not be null
ingestion_1  |  at io.epirus.explorer.ingestion.loader.BlockCommandExtractor.<init>(BlockCommandExtractor.kt:27) ~[loader-2.0.jar!/:na]
ingestion_1  |  at io.epirus.explorer.ingestion.app.IngestionService.<init>(IngestionService.kt:59) ~[classes!/:na]
ingestion_1  |  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
ingestion_1  |  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:na]
ingestion_1  |  at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:na]
ingestion_1  |  at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:na]
ingestion_1  |  at kotlin.reflect.jvm.internal.calls.CallerImpl$Constructor.call(CallerImpl.kt:41) ~[kotlin-reflect-1.3.21.jar!/:1.3.21-release-158 (1.3.21)]
ingestion_1  |  at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106) ~[kotlin-reflect-1.3.21.jar!/:1.3.21-release-158 (1.3.21)]
ingestion_1  |  at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflect_api(KCallableImpl.kt:152) ~[kotlin-reflect-1.3.21.jar!/:1.3.21-release-158 (1.3.21)]
ingestion_1  |  at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:110) ~[kotlin-reflect-1.3.21.jar!/:1.3.21-release-158 (1.3.21)]
ingestion_1  |  at org.springframework.beans.BeanUtils$KotlinDelegate.instantiateClass(BeanUtils.java:788) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
ingestion_1  |  at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:185) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
ingestion_1  |  ... 29 common frames omitted
```

And here is the latest log after start docker
```
web_1        | New Relic for Node.js halted startup due to an error:
web_1        | Error: Not starting without license key!
web_1        |     at onNextTick (/app/node_modules/newrelic/lib/agent.js:227:16)
web_1        |     at processTicksAndRejections (internal/process/task_queues.js:76:11)
web_1        | {"level":30,"time":1638986433355,"pid":678,"hostname":"08b2ff84ef06","msg":"Server listening at http://0.0.0.0:3000","v":1}
web_1        | > Ready on http://localhost:3000
```

I'm using onchain permissioning in network if this information might help.

Here is the screenshot of the web app. Total transaction is 0 even after I just make a transaction
![epirus web app](https://user-images.githubusercontent.com/37577369/145261791-09cb7bfb-54c3-44e9-9305-da46564e24e6.png)

Even it showed up in alethio explorer
![alethio web app](https://user-images.githubusercontent.com/37577369/145261998-d107e431-5a7c-4724-a1ba-4d49bcced976.png)

**Comment by SweeXordious** [comment]
Hello,

In which URL are you accessing the explorer ?

**Comment by fahadh4ilyas** [comment]
> Hello,
> 
> In which URL are you accessing the explorer ? Also, please check if the generated block was caught by the explorer ? (check the blocks tab)

The URL is http://192.168.114.40:8545 which local IP of my machine. It capture total peers correctly though...

![Blocks tab](https://user-images.githubusercontent.com/37577369/145571032-4bf3ced1-e91c-4809-a03a-c12ca11369c6.png)

![Peers tab](https://user-images.githubusercontent.com/37577369/145571082-1b2b2043-88b2-47fb-a0e5-f4f9307d9a5c.png)

**Comment by SweeXordious** [comment]
Yes,  but are you accessing the explorer in `http://localhost` ? to get to the UI ?

**Comment by fahadh4ilyas** [comment]
nope.... I deploy epirus from the same machine so I access it from http://192.168.114.40

**Comment by SweeXordious** [comment]
can you please run : `docker-compose logs` and share everything you see ?

**Comment by fahadh4ilyas** [comment]
Here you go

[docker.log](https://github.com/web3labs/epirus-free/files/7693425/docker.log)

**Comment by SweeXordious** [comment]
It's connected to your geth instance, however it's not able to get the data from it. 
Which flags did you use when starting your geth ?
Do you have: `--rpcaddr 0.0.0.0` and `--rpcvhosts="*"` flags on ?

**Comment by fahadh4ilyas** [comment]
I actually using hyperledger besu, not geth. Here is my parameter

`besu --data-path=./node1/data --genesis-file=genesis.json --p2p-host=192.168.114.40 --permissions-accounts-contract-enabled --permissions-accounts-contract-address "0x0000000000000000000000000000000000008888" --permissions-nodes-contract-enabled --permissions-nodes-contract-address "0x0000000000000000000000000000000000009999" --permissions-nodes-contract-version=2 --rpc-http-enabled --rpc-http-host=192.168.114.40 --rpc-http-port=8545 --rpc-http-cors-origins="*" --rpc-http-api=ADMIN,ETH,NET,PERM,CLIQUE --host-allowlist="*"`

**Comment by SweeXordious** [comment]
For this parameter: `--rpc-http-api=ADMIN,ETH,NET,PERM,CLIQUE`, add also `WEB3` to the list and try again

**Comment by fahadh4ilyas** [comment]
Now, some containers won't running somehow

[docker.log](https://github.com/web3labs/epirus-free/files/7705075/docker.log)

**Comment by SweeXordious** [comment]
`docker-compose down` then
`docker-compose rm`

**Comment by fahadh4ilyas** [comment]
Didn't work and some container exited with code 1
```
CONTAINER ID   IMAGE                                   COMMAND                  CREATED         STATUS                       PORTS                                   NAMES
67256cfa390b   nginx:latest                            "/docker-entrypoint.…"   4 minutes ago   Up 4 minutes                 0.0.0.0:80->80/tcp, :::80->80/tcp       epirus-free_nginx_1
428a2fd29af1   web3labs/epirus-free-web:latest         "/bin/sh -c ./entryp…"   4 minutes ago   Up 4 minutes                 3000/tcp                                epirus-free_web_1
b1ff039c8bc5   web3labs/epirus-free-api:latest         "/bin/sh -c 'exec ja…"   4 minutes ago   Exited (1) 2 minutes ago                                             epirus-free_api_1
5a75fff4d258   web3labs/epirus-free-ingestion:latest   "/bin/sh -c 'exec ja…"   4 minutes ago   Exited (1) 2 minutes ago                                             epirus-free_ingestion_1
6b43f5d0fa82   mongo:latest                            "mongod --logpath=/d…"   4 minutes ago   Exited (132) 4 minutes ago                                           epirus-free_mongodb_1
```

**Comment by SweeXordious** [comment]
share all the logs again please

**Comment by fahadh4ilyas** [comment]
So, I'm trying to do the step from the start. So, I clone the repo, do the `docker-compose pull`, and then run it. The error still the same. Here is the log:

[docker.log](https://github.com/web3labs/epirus-free/files/7705574/docker.log)

**Comment by SweeXordious** [comment]
MongoDB is dying for some reason... did you make any changes to the docker-compose file ?

**Comment by fahadh4ilyas** [comment]
No, I literally just clone the repo and run it.

**Comment by SweeXordious** [comment]
I still can't reproduce.
Also, with the logs you're sharing with me, I don't see any nginx logs.
Please, clone the repository in another folder, navigate to it, then run:
```ssh
$ NODE_ENDPOINT=http://192.168.114.40:8545 docker-compose up
```
Then show me the logs.
Also, if `besu` is showing any erros. please share.

**Comment by SweeXordious** [comment]
and also, if it shows some exception, keep it running for another 10min before copying the logs and sharing them with me.

**Comment by fahadh4ilyas** [comment]
Maybe the problem is the docker images? The docker-compose is pulling the latest images, right?

The nginx logs not showing because the docker-compose stuck and not running anymore. Container `epirus-free_mongodb_1`, `epirus-free_ingestion_1`, and `epirus-free_api_1` is exited with error. Maybe fix that first?

Here is what showing after I tried to open the website

![image](https://user-images.githubusercontent.com/37577369/145983068-48a306c3-4219-4ec9-9f06-0574b15796a6.png)

Here is the log after I open the website

[docker.log](https://github.com/web3labs/epirus-free/files/7710908/docker.log)

**Comment by SweeXordious** [comment]
I am deploying in on a fresh box and it's working. Must be something with what you have right now.
Those containers are stopping because mongo isn't starting, then the ingestion fails because it's not finding a db, then eventually the API dies because it found nothing to work with.

Let's just start from the beginning and do this.

> I still can't reproduce. Also, with the logs you're sharing with me, I don't see any nginx logs. 
> 
> Please, clone the repository in another folder, navigate to it, then run:
> 
> ```
> $ NODE_ENDPOINT=http://192.168.114.40:8545 docker-compose up
> ```
> 
> Then show me the logs. Also, if `besu` is showing any erros. please share.

**Comment by fahadh4ilyas** [comment]
> Maybe the problem is the docker images? The docker-compose is pulling the latest images, right?
> 
> The nginx logs not showing because the docker-compose stuck and not running anymore. Container `epirus-free_mongodb_1`, `epirus-free_ingestion_1`, and `epirus-free_api_1` is exited with error. Maybe fix that first?
> 
> Here is what showing after I tried to open the website
> 
> ![image](https://user-images.githubusercontent.com/37577369/145983068-48a306c3-4219-4ec9-9f06-0574b15796a6.png)
> 
> Here is the log after I open the website
> 
> [docker.log](https://github.com/web3labs/epirus-free/files/7710908/docker.log)

I even tried this on another machine and the result are completely same.

**Comment by SweeXordious** [comment]
Can you do it please another time ? And this time save the logs and share them with me. 
Even if it shows some exceptions, try to let it run for an extra 10min before copying the logs.
Also, don't forget to add the WEB3 param to besu.

If you have it in cloud, and it's possible to give me access, I can login and see what's going on.

**Comment by fahadh4ilyas** [comment]
I finally found the problem. When I tried to watch container creation, the mongodb container somehow exited after run for a couple of seconds. Turns out, this is a problem with mongodb version 5.x. After I changed the `docker-compose.yml` file and change mongodb image to `mongo:4`. The web works miraculously....

**Comment by SweeXordious** [comment]
Awesome.
Are you on a special environment ? On Debian based distributions, this problem doesn't occur.
