### ISSUE TITLE
Epirus error ingestion

### ISSUE THREAD

**Issue by JorgeSC2021** [web3labs/epirus-free#45]
Good morning everyone, I have a problem running the free version of epirus from we3labs, when executing docker-compose up, it first has problems with synchrony when raising the containers, since it starts making requests before they are raised, which I corrected with the "-d" parameter and wait a few minutes to start.

After the containers go up, if I launch the docker-compose up again, and as the service starts to get up, I have an error in the ingestion, it returns an error in several parts of this ingestion container, which is "Expected URL scheme 'http' or 'https' but no colon was found".

I installed this on a private EC2 instance, pointing to a Hyperledger Besu network installed within the same VPC from which I am running Epirus.

Thank you

**Comment by JorgeSC2021** [comment]
ok, los commands are:

- NODE_ENDPOINT=http://xx.xx.xx.xx:8545 docker-compose up -d
- wait for few minutes for containers start good
- NODE_ENDPOINT=http://xx.xx.xx.xx:8545 docker-compose up

In others installation i only use the last command, i dont known what it depends on.  I go to check your last comment, thank you, i go to review and write if that was the problem

**Comment by JorgeSC2021** [comment]
I check connection, i find some problems, but yet have the same result, i do it telnet on IP public and port 8546, and connection was ok.

**Comment by SweeXordious** [comment]
If RPC is exposed on `8546`, why are you using this address: `http://xx.xx.xx.xx:8545/` with port `8545`? 
Shouldn't it be `http://xx.xx.xx.xx:8546/` ?

**Comment by JorgeSC2021** [comment]
Sorry everyone, that was a problem completelly about AWS permissions.  I had to configure networks communications and deploy epirus with root admin.

SweeXordious, i am using 8546 port, that was a bad writing, thank you for your help.
