### ISSUE TITLE
ingestion, API service exit in docker since Mongo fails to to start

### ISSUE THREAD

**Issue by denkab** [web3labs/epirus-free#47]
Hi!

In my current configuration, docker-compose command results in deficient epirius instance, because API exits.

`epirus-free_mongodb_1 exited with code 132`

`api_1        | Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=mongodb:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketException: mongodb}, caused by {java.net.UnknownHostException: mongodb}}]`
followed by

`epirus-free_api_1 exited with code 1`

**Comment by denkab** [comment]
Changing "mongo:latest" -> "mongo:4" in docker-compose.yml allows Mongo to start and entire contraption starts to function.

**Comment by SweeXordious** [comment]
@denkab is your issue solved?
If not, we will need to know more logs to dig the issue.

**Comment by denkab** [comment]
It is solved for me but may appear for others... Is "mongo:latest" a true prerequisite for the product to work correctly?

**Comment by SweeXordious** [comment]
Can you please share the logs of mongo when you use the latest tag?
We might need to specify the version of mongo as new versions might have breaking changes that we still don't support.
Knowing the reason why latest fails is important to decide.

**Comment by SweeXordious** [comment]
Change the version back to latest.
Run epirus free then run:

```shell
docker-compose logs
```

And share the whole output.

**Comment by jschulman** [comment]
mongo:5.0.8 doesn't even start.  There are no errors in the log at all.  it's kinda weird.

anyway, changing it to mongo:4 allows it to start up just fine.

**Comment by SweeXordious** [comment]
Opened request in here: https://github.com/web3labs/epirus-free/issues/48
Closing.
